name: Test

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",  os: windows-latest, cc: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - { name: "Windows Latest MinGW", os: windows-latest, cc: "gcc" }
        - { name: "Ubuntu Latest GCC",    os: ubuntu-latest, cc: "gcc" }
        - { name: "OSX Latest Clang",     os: macos-latest, cc: "clang" }
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        cmake -E make_directory build
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE --verbose ..
        cmake --build . --config $BUILD_TYPE --verbose
    - name: Test
      working-directory: build
      if: "!startsWith(matrix.config.os, 'windows')"
      run: ctest -C $BUILD_TYPE --output-on-failure --verbose
